# Generated by Django 5.1.1 on 2024-10-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
