# Generated by Django 5.1.1 on 2024-10-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
